### ISSUE TITLE
Update to Sequelize 4

### ISSUE THREAD

**Issue by brunoprela** [Wsiegenthaler/sequelize-embed#1]
Hello, this is a wonderful project. Was wondering if you were planning on upgrading to Sequelize 4, specifically for the embedding feature.

**Comment by Wsiegenthaler** [comment]
Thanks! I don't believe there are any breaking changes to the Sequelize 4 API as far as this library is concerned. Coverage isn't 100% - so no guarantees - but all the tests pass for both v3 and v4. I've just pushed an update so the tests run against v4 by default (see 1.0.0). Do let me know if you run into any issues.

**Comment by brunoprela** [comment]
I have two models, User and ContactInfo. User hasOne ContactInfo.
 
This is how I am calling embed:
`
var helpers = embed.util.helpers;
            var mkIncludes = helpers.includes, mkInclude = helpers.include;

            var include = mkIncludes(mkInclude(models.ContactInfo));
            var opts = { reload: { include } };

            console.log('args: ' + {...args});

            embed.update(models.User, {...args}, include, opts)
`

This actually works to update the User but I keep getting an error when it gets to the ContactInfo. I know this is most likely not to do with embed, but I was wondering if you'd ever run into this problem. I've checked all my typing and everything on my models.

`args = { id: '1',
  firstName: 'Newname',
  lastName: 'prelaa',
  username: 'YOO',
  email: 'prelab@ggoodfs.edu',
  password: 'password',
  contactInfo: { id: '1', email: 'LOL@sfds.edu' } }

Executing (52b1ee20-bc3f-46d1-9e8c-4e8e6ee3c8ee): START TRANSACTION;
Executing (52b1ee20-bc3f-46d1-9e8c-4e8e6ee3c8ee): UPDATE "users" SET "id"='1',"firstName"='Newname',"lastName"='prelaa',"username"='YOO',"email"='prelab@ggoodfs.edu',"password"='password',"updated_at"='2018-01-17 22:25:35.939 +00:00' WHERE "id" = '1'
Executing (52b1ee20-bc3f-46d1-9e8c-4e8e6ee3c8ee): COMMIT;

Unhandled rejection TypeError: Cannot read property 'name' of undefined
`

If you have any ideas, I'd appreciate it.

**Comment by Wsiegenthaler** [comment]
When constructing your includes, rather than passing in the model of the associated type (i.e. models.ContactInfo), you'll need to pass the association object (User.ContactInfo):

`
User.ContactInfo = User.hasOne(ContactInfo, { as: 'contactInfo', foreignKey: 'userId' });

const include = mkIncludes(mkInclude(User.ContactInfo));
`

**Comment by brunoprela** [comment]
Thank you for your help. Changing that resulted in the error going away, but now the contactInfo object ends up getting deleted. I simplified the test I've been trying, and included more info from my project.

The **user.js** and **contactInfo.js** models are defined as follows (I stripped out most of it to reduce complexity):

```
export default (sequelize, DataTypes) => {
	const User = sequelize.define('user', {
	    /*
	        Model representing a user.
	     */
        dateCreated: {
		    type: DataTypes.DATE,
            defaultValue: DataTypes.NOW,
            allowNull: false,
        },
		firstName: {
	        type: DataTypes.STRING,
            allowNull: false,
        },
		lastName: {
	        type: DataTypes.STRING,
            allowNull: false
        },
	});

	User.associate = (models) => {
        User.ContactInfo = User.hasOne(models.ContactInfo, {as: 'contactInfo', foreignKey: 'userId' });
    };

	return User;
};
```

```
export default (sequelize, DataTypes) => {
    const ContactInfo = sequelize.define('contactInfo', {
        email: type: DataTypes.STRING,
    });

    return ContactInfo;
};
```

My **models/index.js** file is define as follows:

```
import Sequelize from 'sequelize';
import path from 'path';
const env = process.env.NODE_ENV || "development";
const config = require(path.join(__dirname, '..', 'config', 'config.json'))[env];

const sequelize = new Sequelize(config.database, config.username, config.password, {
    dialect: config.dialect,
});

// importing models (ex. from user.js and contactInfo.js)
const models = {
    ContactInfo: sequelize.import('./contactInfo'),
    User: sequelize.import('./user'),
};

// creating associations
Object.keys(models).forEach((modelName) => {
    if('associate' in models[modelName]){
        models[modelName].associate(models);
    }
});

models.sequelize = sequelize;
models.Sequelize = Sequelize;

export default models;
```

And I am calling embed like so. I have tried both with the opts argument and without it.

```
import models from '../models';
const embed = require('sequelize-embed')(models.sequelize);

const helpers = embed.util.helpers;
const mkIncludes = helpers.includes, mkInclude = helpers.include;

const include = mkIncludes(mkInclude(models.User.ContactInfo));
const opts = { reload: { include } };

console.log({...args});

embed.update(models.User, {...args}, include, opts)
```

In the SQL logging output there seems to be a DELETE operation, which appears to be deleting the contactInfo instead of updating it. This time around the arguments I put in are simpler and only seek to change the email of the contactInfo.

```
args = { id: '1', contactInfo: { id: '1', email: 'LOL@sfds.edu' } }

Executing (71f0d2cb-e321-4775-bdcf-42b15add5420): START TRANSACTION;
Executing (71f0d2cb-e321-4775-bdcf-42b15add5420): UPDATE "users" SET "id"='1',"updated_at"='2018-01-18 18:24:47.648 +00:00' WHERE "id" = '1'
Executing (default): SELECT "id", "email", "createdAt", "updatedAt",  "userId" FROM "contactInfos" AS "contactInfo" WHERE "contactInfo"."userId" = '1' LIMIT 1;
Executing (71f0d2cb-e321-4775-bdcf-42b15add5420): DELETE FROM "contactInfos" WHERE "id" IN (SELECT "id" FROM "contactInfos" WHERE "id" = 1 LIMIT 1)
Executing (default): SELECT "id", "email", "createdAt", "updatedAt", "userId" FROM "contactInfos" AS "contactInfo" WHERE "contactInfo"."id" = '1';
Executing (71f0d2cb-e321-4775-bdcf-42b15add5420): UPDATE "contactInfos" SET "email"='LOL@sfds.edu',"userId"='1',"updatedAt"='2018-01-18 18:24:47.661 +00:00' WHERE "id" = 1
Executing (71f0d2cb-e321-4775-bdcf-42b15add5420): COMMIT;
Executing (default): SELECT "user"."id",  "user"."dateCreated", "user"."firstName", "user"."lastName", "user"."createdAt", "user"."updatedAt", "contactInfo"."id" AS "contactInfo.id", "contactInfo"."email" AS "contactInfo.email", "contactInfo"."createdAt" AS "contactInfo.createdAt", "contactInfo"."updatedAt" AS "contactInfo.updatedAt", "contactInfo"."userId" AS "contactInfo.userId" FROM "users" AS "user" LEFT OUTER JOIN "contactInfos" AS "contactInfo" ON "user"."id" = "contactInfo"."userId" WHERE "user"."id" = '1';
```

**Comment by Wsiegenthaler** [comment]
Guess you found a bug after all! I've opened #4 and should have a fix out later tonight.

**Comment by brunoprela** [comment]
Yep that is it, thank you. I'm developing my API with graphql and it stringifies ids. Manually making them ints fixed the problem. Will let you know if I find more issues. This is a great feature that just about everyone using Sequelize would/should want so I'm surprised it's not super popular.

**Comment by Wsiegenthaler** [comment]
Okay, we should be good to go. FYI, I also renamed the include helpers to `mkInclude` and `mkIncludes` since that seems clearer.
```
const { mkInclude, mkIncludes } = embed.util.helpers;
```
Thanks for helping to shake this bug out!
