### ISSUE TITLE
Need an example for transaction

### ISSUE THREAD

**Issue by Tri-Vi** [Wsiegenthaler/sequelize-embed#11]
Does anyone know how to use transaction with this library? Or is there any example that uses transaction?

**Comment by Wsiegenthaler** [comment]
Hi, thanks for your interest in the project! You should be able to pass your transaction using the "transaction" field of the options parameter. This is documented in the README, but I agree it would be good to have an example too. I'll try to add one when I get a chance.

I'm closing this but let me know if you're still having trouble.

**Comment by Tri-Vi** [comment]
> Hi, thanks for your interest in the project! You should be able to pass your transaction using the "transaction" field of the options parameter. This is documented in the README, but I agree it would be good to have an example too. I'll try to add one when I get a chance.
> 
> I'm closing this but let me know if you're still having trouble.

Hi, thanks for your reply. I already read the README but it's hard to know how to implement transaction with association without a real example.

**Comment by Wsiegenthaler** [comment]
Absolutely, sorry about that. I haven't tested it but here's a simple example that should give you the gist...

```js
const sequelize = require('sequelize')
const embed = require('sequelize-embed')(sequelize)
const { mkInclude } = embed.util.helpers

// Define schema
let Artist = sequelize.define('Artist', { name: Sequelize.STRING })
let Album = sequelize.define('Album', { name: Sequelize.STRING, year: Sequelize.INTEGER })

// Define association and includes
Artist.Albums = Artist.hasMany(Album, { as: 'albums', foreignKey: 'artistId' })
let includeArtistAndAlbums = mkInclude(Artist.Albums)

// Define an artist and some albums
let artist = {
  name: 'Kruanghbin',
  albums: [
    { name: 'The Universe Smiles upon You', year: 2015 },
    { name: 'Con Todo El Mundo', year: 2018 },
    { name: 'Hasta El Cielo', year: 2019 },
    { name: 'Texas Sun', year: 2020 },
    { name: 'Mordechai', year: 2020 }
  ]
}

// Insert records using external transaction and commit
let transaction = sequelize.transaction()
embed.insert(Artist, artist, includeArtistAndAlbums, { transaction })
transaction.commit()
```
