### ISSUE TITLE
TypeError: Cannot read property 'associationAccessor' of undefined

### ISSUE THREAD

**Issue by stevez86** [Wsiegenthaler/sequelize-embed#5]
Hi I just stumbled upon this package and think it's exactly what I'm looking for however I came across this error when trying to save an object that only includes data for some of the provided associations:

```
TypeError: Cannot read property 'associationAccessor' of undefined
    at include.map.inc (.../node_modules/sequelize-embed/src/util.js:54:41)
    at Array.map (<anonymous>)
    at prune (.../node_modules/sequelize-embed/src/util.js:53:13)
    at include.map.inc (.../node_modules/sequelize-embed/src/util.js:60:9)
    at Array.map (<anonymous>)
    at prune (.../node_modules/sequelize-embed/src/util.js:53:13)
    at include.map.inc (.../node_modules/sequelize-embed/src/util.js:60:9)
    at Array.map (<anonymous>)
    at prune (.../node_modules/sequelize-embed/src/util.js:53:13)
    at include.map.inc (.../node_modules/sequelize-embed/src/util.js:60:9)
    at Array.map (<anonymous>)
    at prune (.../node_modules/sequelize-embed/src/util.js:53:13)
    at instance.reload.then.inst (.../node_modules/sequelize-embed/src/embed.js:147:26)
From previous event:
    at reload (.../node_modules/sequelize-embed/src/embed.js:146:58)
    at action.tap.catch.then.inst (.../node_modules/sequelize-embed/src/embed.js:26:23)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

https://github.com/Wsiegenthaler/sequelize-embed/blob/b0c930ec92b64ab4fa999fe05fa26da777215856/src/util.js#L54

I can get the error to go away when I don't include the unnecessary embed associations however I'd prefer to include them as I'm not sure which data is going to be updated.

Here are examples, not: location and profiles are associations on basics which is an association on basics which is an association on resume:

```
import {
  Resume,
  JsonResume,
  JsonResumeBasics
} from 'data/models';

const resumeEmbedAssociations = [
  mkInclude(
    Resume.JsonResume,
    mkInclude(
      JsonResume.JsonResumeBasics,
      mkInclude(
        JsonResumeBasics.JsonResumeBasicsLocation,
        JsonResumeBasics.JsonResumeBasicsProfile,
      ),
    ),
  ),
];

const updateResume = {
  id: '67fc7ce0-9e51-11e8-ae55-1dd8aec4856d',
  userId: 'fe07daa0-9e50-11e8-ae55-1dd8aec4856d',
  jsonResume: {
    basics: {
      name: 'name',
      label: '123',
      picture: 'picture',
      email: 'email@email.com',
      phone: 'phone',
      website: 'ddddd',
      location: null,
      profiles: [],
    },
  },
};

embed.update(
            Resume,
            updateResume,
            resumeEmbedAssociations,
          );
```

**Comment by stevez86** [comment]
I was able to move forward by setting the `reload: { prune: false }` in options. Still new to this package so please let me know if I'm doing something incorrectly.

**Comment by stevez86** [comment]
Looks like I was using the mkInclude incorrectly and after changing to this it worked:

```
const resumeEmbedAssociations = [
  mkInclude(
    Resume.JsonResume,
    mkInclude(
      JsonResume.JsonResumeBasics,
      mkInclude(JsonResumeBasics.JsonResumeBasicsLocation),
      mkInclude(JsonResumeBasics.JsonResumeBasicsProfile),
    ),
  )
]
```

**Comment by Wsiegenthaler** [comment]
Glad you figured it out. Your second attempt looks much better.

I should probably mention that the `update` operation expects the entire record (including all associations) and will delete any preexisting associations if they aren't provided to the call. This is in contrast to semantics more akin to "patch" where if you omit, say, your 'location' or 'profile' fields, those associations will simply be ignored rather than deleted. You may want to enable Sequelize logging and trace through the actual SQL just to make sure it's doing what you expect.

Anyway, thanks for trying out the project. Let me know if there's anything else I can help you with!

**Comment by stevez86** [comment]
It seems to be exactly what I needed. Not sure if you want a pull request for this but this function takes a sequelize association and converts it to the embed one; might be a good helper utility for this project.

```
const toEmbedAssociations = ({ association, include = [] }) => [
  mkInclude(association, ...include.map(toEmbedAssociations)),
];
```

**Comment by stevez86** [comment]
This will recursively add the mkInclude down all levels. Not quite sure the point of mkInclude, it'd be nice if we could just pass in the sequelize association
