### ISSUE TITLE
Update with more than one records having the same primary key succeeds

### ISSUE THREAD

**Issue by martinlehotsky** [Wsiegenthaler/sequelize-embed#8]
Hello,

calling update with two or more records having same primary key silently succeeds if such a primary key is already in database. Of course, no other record with same primary key is in reality added to database. It is confusing for user however, he thinks he succeeded adding another record with same primary key. 
From the source code I see this behavior is caused by:
1. diff in util.js skips duplicates. However, even after I changed the code to consider also duplicates as new records:
2. updateOrInsert in embed.js firstly tries to find data in db (findOne) and in case of success it does just update

Are you going to fix it or is it by design?

Another question, do you plan to upgrade to Sequelize 5?

thanks

**Comment by Wsiegenthaler** [comment]
Duplicate primary keys isn't something _sequelize-embed_ currently validates, the thinking being that this is unnecessary overhead to impose on applications which always have well formed arguments.  I'm willing to hear your case for adding it but I think it would be preferable for this validation to be done by the application.

I've used _sequelize-embed_ with one of the _Sequelize v5_ betas and didn't run into any issues. To my knowledge v5 doesn't break compatibility with this library but let me know if you run into any problems.
